name: Deploy Production
on:
  push:
    branches:
      - main  # <--- OJO: Esto solo se activa con la rama main
jobs:
  web-deploy:
    name: 🎉 Deploy to Production
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./  # <--- IMPORTANTE: Esto lo deja en la raíz (public_html)
        protocol: ftps
        security: loose
